appConfig: weaver.toml
repo: h21565897

listeners:
  - name: gotosocial
    public: true
storageSpec:
  volumes:
    - name: app-config
      configMap:
        name: gotosocial-config
  volumeMounts:
    - name: app-config
      mountPath: /weaver/config.yaml
      subPath: config.yaml
      readOnly: true
